// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlgjotlconkvudzldodq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZ2pvdGxjb25rdnVkemxkb2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTc4NTMsImV4cCI6MjA2NTQ5Mzg1M30.gNkjMy-JsQFbpuNYaofylBqgeUKPTnXGR3slvIynBQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);